#pragma once

#include <Geode/Geode.hpp>
#include <Geode/modify/EditorUI.hpp>

using namespace geode::prelude;

class $modify(REEditorUI, EditorUI) {
	
    static EditorUI* create_(LevelEditorLayer* editorLayer);
    static int getRandomStartKey(int specialTemplate);
    static int getSmartObjectKey(int key, GJSmartDirection direction);
    static int smartTypeForKey(int key);
    virtual void draw();
    virtual bool ccTouchBegan(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    virtual void ccTouchMoved(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    virtual void ccTouchEnded(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    virtual void ccTouchCancelled(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    virtual void registerWithTouchDispatcher();
    virtual void keyBackClicked();
    virtual void keyDown(cocos2d::enumKeyCodes key, double timestamp);
    virtual EditorUI* getUI();
    virtual void setIDPopupClosed(SetIDPopup* popup, int value);
    virtual void FLAlert_Clicked(FLAlertLayer* layer, bool btn2);
    virtual void updateTransformControl();
    virtual void transformChangeBegin();
    virtual void transformChangeEnded_();
    virtual cocos2d::CCNode* getTransformNode();
    virtual void transformScaleXChanged(float scaleX);
    virtual void transformScaleYChanged(float scaleY);
    virtual void transformScaleXYChanged(float scaleX, float scaleY);
    virtual void transformSkewXChanged(float skewX);
    virtual void transformSkewYChanged(float skewY);
    virtual void transformRotationXChanged(float rotationX);
    virtual void transformRotationYChanged(float rotationY);
    virtual void transformRotationChanged(float rotation);
    virtual void transformResetRotation();
    virtual void transformRestoreRotation();
    virtual void songStateChanged();
    virtual void colorSelectClosed(cocos2d::CCNode* popup);
    virtual void keyUp(cocos2d::enumKeyCodes key, double timestamp);
    virtual void scrollWheel(float y, float x);
    virtual void angleChangeBegin();
    virtual void angleChangeEnded_();
    virtual void angleChanged(float rotation);
    virtual void updateScaleControl();
    virtual void anchorPointMoved(cocos2d::CCPoint anchorPoint);
    virtual void scaleChangeBegin();
    virtual void scaleChangeEnded_();
    virtual void scaleXChanged(float scaleX, bool lock);
    virtual void scaleYChanged(float scaleY, bool lock);
    virtual void scaleXYChanged(float scaleX, float scaleY, bool lock);
    void activateRotationControl(cocos2d::CCObject* sender);
    void activateScaleControl(cocos2d::CCObject* sender);
    void activateTransformControl(cocos2d::CCObject* sender);
    void addObjectsToSmartTemplate(GJSmartTemplate* smartTemplate, cocos2d::CCArray* objects);
    void addSnapPosition_(cocos2d::CCPoint position);
    void alignObjects(cocos2d::CCArray* objects, bool axisY);
    void applyOffset(GameObject* object);
    cocos2d::CCPoint applySpecialOffset(cocos2d::CCPoint position, GameObject* object, cocos2d::CCPoint offset);
    bool arrayContainsClass_(cocos2d::CCArray* objects, int classType);
    void assignNewGroups(bool groupY);
    bool canAllowMultiActivate_(GameObject* object, cocos2d::CCArray* objects);
    bool canSelectObject(GameObject* object);
    void centerCameraOnObject_(GameObject* object);
    void changeSelectedObjects_(cocos2d::CCArray* objects, bool ignoreFilter);
    cocos2d::CCPoint checkDiffAfterTransformAnchor(cocos2d::CCPoint diff, cocos2d::CCArray* objects);
    void checkLiveColorSelect();
    void clickOnPosition(cocos2d::CCPoint position);
    void closeLiveColorSelect();
    void closeLiveHSVSelect();
    void colorSelectClosed_(cocos2d::ccColor3B color);
    void constrainGameLayerPosition_();
    void constrainGameLayerPosition(float x, float y);
    int convertKeyBasedOnNeighbors(int smartKey, int objectID, cocos2d::CCPoint position, cocos2d::CCArray* objects);
    int convertToBaseKey(int objectID);
    gd::string copyObjects(cocos2d::CCArray* objects, bool copyColors, bool sort);
    gd::string copyObjectsDetailed_(cocos2d::CCArray* objects);
    cocos2d::CCArray* createCustomItems();
    GameObject* createEdgeForObject(GameObject* object, int type);
    void createExtraObject(int id, cocos2d::CCPoint position, GameObject* object, cocos2d::CCArray* objects, int zOrder, int editorLayer);
    cocos2d::CCArray* createExtras_(cocos2d::CCArray* objects);
    void createExtrasForObject(int id, GameObject* object, cocos2d::CCArray* objects);
    void createGlow_();
    void createLoop();
    void createMoveMenu();
    void createNewKeyframeAnim();
    GameObject* createObject(int objectID, cocos2d::CCPoint position);
    cocos2d::CCArray* createOutlines(cocos2d::CCArray* objects);
    void createPrefab(GJSmartTemplate* smartTemplate, gd::string key, int id);
    cocos2d::CCArray* createRockBases(cocos2d::CCArray* objects);
    cocos2d::CCArray* createRockEdges(cocos2d::CCArray* objects);
    void createSmartObjectsFromTemplate(GJSmartTemplate* smartTemplate, cocos2d::CCArray* objects, bool useNearby, bool dontDelete, bool referenceOnly, bool dontPaste);
    void createSmartObjectsFromType(int type, cocos2d::CCArray* objects, bool extras, bool dontDelete);
    UndoObject* createUndoObject(UndoCommand command, bool addToList);
    void createUndoSelectObject(bool redo);
    void deactivateRotationControl_();
    void deactivateScaleControl();
    void deactivateTransformControl();
    void deleteObject_(GameObject* object, bool noUndo);
    void deleteSmartBlocksFromObjects(cocos2d::CCArray* objects);
    void deleteTypeFromObjects_(int id, cocos2d::CCArray* objects);
    void deselectAll();
    void deselectObject_();
    void deselectObject(GameObject* object);
    void deselectObjectsColor();
    void deselectTargetPortals();
    void disableButton_(CreateMenuItem* button);
    void doCopyObjects(bool withColor);
    void doPasteInPlace_(bool withColor);
    void doPasteObjects(bool withColor);
    void dynamicGroupUpdate(bool reGroup);
    int edgeForObject_(int id, int type);
    bool editButton2Usable();
    bool editButtonUsable();
    void editColor();
    bool editColorButtonUsable_();
    void editGroup(cocos2d::CCObject* sender);
    void editHSV();
    void editObject(cocos2d::CCObject* sender);
    void editObject2(cocos2d::CCObject* sender);
    void editObject3_(cocos2d::CCObject* sender);
    void editObjectSpecial(int type);
    int editorLayerForArray_(cocos2d::CCArray* objects, bool layer2);
    void enableButton_(CreateMenuItem* button);
    void findAndSelectObject(int id, bool useUniqueID);
    void findSnapObject(cocos2d::CCArray* objects, float offset);
    void findSnapObject(cocos2d::CCPoint position, float offset);
    void findTriggerTest_();
    void flipObjectsX(cocos2d::CCArray* objects);
    void flipObjectsY(cocos2d::CCArray* objects);
    CCMenuItemSpriteExtra* getButton_(char const* text, int width, cocos2d::SEL_MenuHandler selector, cocos2d::CCMenu* menu);
    CreateMenuItem* getCreateBtn(int id, int bg);
    CreateMenuItem* getCreateMenuItemButton_(cocos2d::CCSprite* sprite, cocos2d::SEL_MenuHandler selector, cocos2d::CCMenu* menu, float scale, int background, cocos2d::CCPoint offset);
    GameObject* getCycledObject_(cocos2d::CCArray* objects, bool dontSkipSelected);
    void getEditColorTargets(ColorAction*& mainColor, ColorAction*& detailColor, EffectGameObject*& object);
    cocos2d::CCPoint getGridSnappedPos_(cocos2d::CCPoint pos);
    cocos2d::CCPoint getGroupCenter(cocos2d::CCArray* objects, bool absolute);
    void getGroupInfo_(GameObject* selectedObject, cocos2d::CCArray* selectedObjects, int& objectID, int& classType, int& objectType);
    cocos2d::CCPoint getLimitedPosition(cocos2d::CCPoint position);
    CCMenuItemSpriteExtra* getModeBtn_(char const* frameName, int tag);
    cocos2d::CCNode* getNeighbor(int smartKey, cocos2d::CCPoint position, GJSmartDirection direction, cocos2d::CCArray* objects);
    cocos2d::CCPoint getRelativeOffset_(GameObject* object);
    cocos2d::CCArray* getSelectedObjects();
    CCMenuItemSpriteExtra* getSimpleButton_(gd::string frameName, cocos2d::SEL_MenuHandler selector, cocos2d::CCMenu* menu);
    SmartGameObject* getSmartNeighbor(SmartGameObject* object, cocos2d::CCPoint position, GJSmartDirection direction, cocos2d::CCArray* objects);
    float getSnapAngle_(GameObject* object, cocos2d::CCArray* objects);
    CCMenuItemSpriteExtra* getSpriteButton_(char const* spriteFrameName, cocos2d::SEL_MenuHandler selector, cocos2d::CCMenu* menu, float scale);
    CCMenuItemSpriteExtra* getSpriteButton_(char const* spriteFrameName, cocos2d::SEL_MenuHandler selector, cocos2d::CCMenu* menu, float scale, int background, cocos2d::CCPoint offset);
    CCMenuItemSpriteExtra* getSpriteButton_(cocos2d::CCSprite* sprite, cocos2d::SEL_MenuHandler selector, cocos2d::CCMenu* menu, float scale, int background, cocos2d::CCPoint offset);
    cocos2d::CCPoint getTouchPoint_(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    GJTransformState& getTransformState_();
    float getXMin(int offset);
    bool init(LevelEditorLayer* editorLayer);
    bool isLiveColorSelectTrigger_(GameObject* object);
    bool isSpecialSnapObject(int id);
    bool liveEditColorUsable_();
    CreateMenuItem* menuItemFromObjectString(gd::string str, int id);
    cocos2d::CCPoint moveForCommand(EditCommand command);
    void moveGamelayer(cocos2d::CCPoint offset);
    void moveObject(GameObject* object, cocos2d::CCPoint offset);
    void moveObjectCall(EditCommand command);
    void moveObjectCall(cocos2d::CCObject* sender);
    cocos2d::CCPoint offsetForKey(int id);
    void onAssignNewGroupID();
    void onColorFilter(cocos2d::CCObject* sender);
    void onCopy(cocos2d::CCObject* sender);
    void onCopyState(cocos2d::CCObject* sender);
    bool onCreate();
    void onCreateButton(cocos2d::CCObject* sender);
    void onCreateObject(int id);
    void onDelete(cocos2d::CCObject* sender);
    void onDeleteAll_(cocos2d::CCObject* sender);
    void onDeleteCustomItem(cocos2d::CCObject* sender);
    void onDeleteInfo(cocos2d::CCObject* sender);
    void onDeleteSelected(cocos2d::CCObject* sender);
    void onDeleteSelectedType(cocos2d::CCObject* sender);
    void onDeleteStartPos(cocos2d::CCObject* sender);
    void onDeselectAll(cocos2d::CCObject* sender);
    void onDuplicate(cocos2d::CCObject* sender);
    void onEditColor(cocos2d::CCObject* sender);
    void onFindObject(cocos2d::CCObject* sender);
    void onGoToBaseLayer(cocos2d::CCObject* sender);
    void onGoToLayer(cocos2d::CCObject* sender);
    void onGroupDown(cocos2d::CCObject* sender);
    void onGroupIDFilter(cocos2d::CCObject* sender);
    void onGroupSticky(cocos2d::CCObject* sender);
    void onGroupUp(cocos2d::CCObject* sender);
    void onLockLayer(cocos2d::CCObject* sender);
    void onNewCustomItem(cocos2d::CCObject* sender);
    void onPaste(cocos2d::CCObject* sender);
    void onPasteColor(cocos2d::CCObject* sender);
    void onPasteInPlace_(cocos2d::CCObject* sender);
    void onPasteState(cocos2d::CCObject* sender);
    void onPause(cocos2d::CCObject* sender);
    void onPlayback(cocos2d::CCObject* sender);
    void onPlaytest(cocos2d::CCObject* sender);
    void onResetSpecialFilter(cocos2d::CCObject* sender);
    void onSelectBuildTab(cocos2d::CCObject* sender);
    void onSettings(cocos2d::CCObject* sender);
    void onStickyToggle(cocos2d::CCObject* sender);
    void onStopPlaytest(cocos2d::CCObject* sender);
    void onTargetIDChange(int change);
    void onToggleGuide_(EffectGameObject* object);
    void onToggleSelectedOrder_(EffectGameObject* object);
    void onToggleTraceIn_(GameObject* object);
    void onToggleTraceOut_(EffectGameObject* object);
    void onUngroupSticky(cocos2d::CCObject* sender);
    void onUpdateDeleteFilter(cocos2d::CCObject* sender);
    void orderDownCustomItem(cocos2d::CCObject* sender);
    void orderUpCustomItem(cocos2d::CCObject* sender);
    cocos2d::CCArray* pasteObjects(gd::string str, bool withColor, bool noUndo);
    void playCircleAnim_(cocos2d::CCPoint position, float radius, float duration);
    void playerTouchBegan_(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    void playerTouchEnded_(cocos2d::CCTouch* touch, cocos2d::CCEvent* event);
    void playtestStopped();
    bool positionIsInSnapped_(cocos2d::CCPoint position);
    cocos2d::CCPoint positionWithoutOffset_(GameObject* object);
    void processSelectObjects(cocos2d::CCArray* objects);
    void processSmartObjectsFromType(int type, cocos2d::CCArray* objects, cocos2d::CCArray* objects2, cocos2d::CCArray* objects3, cocos2d::CCArray* objects4);
    void recreateButtonTabs_();
    void redoLastAction(cocos2d::CCObject* sender);
    void reloadCustomItems();
    void removeOffset(GameObject* object);
    void replaceGroupID(GameObject* object, int oldID, int newID);
    void repositionObjectsToCenter(cocos2d::CCArray* objects, cocos2d::CCPoint position, bool absolute);
    void resetObjectEditorValues_(cocos2d::CCArray* objects);
    void resetSelectedObjectsColor();
    void resetUI();
    void rotateObjects(cocos2d::CCArray* objects, float rotation, cocos2d::CCPoint pivotPoint);
    float rotationforCommand_(EditCommand command);
    void scaleObjects(cocos2d::CCArray* objects, float scaleX, float scaleY, cocos2d::CCPoint pivotPoint, ObjectScaleType type, bool lockMove);
    void selectAll_();
    void selectAllWithDirection(bool left);
    void selectBuildTab(int tabIndex);
    void selectObject(GameObject* object, bool ignoreFilter);
    void selectObjects(cocos2d::CCArray* objects, bool ignoreFilter);
    void selectObjectsInRect_(cocos2d::CCRect rect);
    void setupCreateMenu();
    void setupDeleteMenu();
    void setupEditMenu_();
    void setupTransformControl_();
    bool shouldDeleteObject(GameObject* object);
    bool shouldSnap_(GameObject* object);
    void showDeleteConfirmation_();
    void showLiveColorSelectForMode(int colorID);
    void showLiveColorSelectForModeSpecial_(int colorID);
    void showMaxBasicError();
    void showMaxCoinError_();
    void showMaxError();
    void showUI(bool show);
    void sliderChanged(cocos2d::CCObject* sender);
    cocos2d::CCSprite* spriteFromObjectString(gd::string str, bool absoluteCenter, bool useGroup, int objLimit, cocos2d::CCArray* objects, cocos2d::CCArray* group, GameObject* groupParent);
    void toggleDuplicateButton_();
    void toggleEditObjectButton();
    void toggleEnableRotate(cocos2d::CCObject* sender);
    void toggleFreeMove(cocos2d::CCObject* sender);
    void toggleLockUI_(bool lockUI);
    void toggleMode(cocos2d::CCObject* sender);
    void toggleObjectInfoLabel();
    void toggleSnap(cocos2d::CCObject* sender);
    void toggleSpecialEditButtons();
    void toggleSwipe(cocos2d::CCObject* sender);
    void transformObject(GameObject* object, EditCommand command, bool noOffset);
    void transformObjectCall(EditCommand command);
    void transformObjectCall(cocos2d::CCObject* sender);
    void transformObjects(cocos2d::CCArray* objs, cocos2d::CCPoint anchor, float scaleX, float scaleY, float rotateX, float rotateY, float warpX, float warpY);
    void transformObjectsActive();
    void transformObjectsReset_();
    void triggerSwipeMode();
    void tryUpdateTimeMarkers_();
    void undoLastAction(cocos2d::CCObject* object);
    void updateButtons();
	void updateCreateMenu(bool selectTab);
    void updateDeleteButtons();
    void updateDeleteMenu_();
    void updateEditButtonColor(int tag, cocos2d::ccColor3B color);
    void updateEditColorButton();
    void updateEditMenu_();
    void updateGridNodeSize();
    void updateGridNodeSize_(int objectID);
    void updateGroupIDBtn2_();
    void updateGroupIDLabel();
    void updateObjectInfoLabel();
    void updatePlaybackBtn();
    void updateSlider();
    void updateSpecialUIElements_();
    void updateStickyControls_();
    void updateZoom(float zoom);
    float valueFromXPos_(float xPos);
    float xPosFromValue_(float value);
    void zoomGameLayer_(bool zoomingIn);
    void zoomIn(cocos2d::CCObject* sender);
    void zoomOut(cocos2d::CCObject* sender);

    static uint64_t s_rngSeed;
};